In [1]:
import numpy as np
#transepose
"""
transpose of a matrix means to transform the rows of a matrix to columns and
transform of the columns into rowa . for example a transpose matrix of an 2x3 matrix 
will form into a 3x2 matrix 
"""

matrix=np.array([[1,2,3,4],[4,5,6,7]])
print('given matrix : ')
print(matrix)
print('transepose matrix : ')
transposed=matrix.transpose()
print(transposed)

given matrix : 
[[1 2 3 4]
 [4 5 6 7]]
transepose matrix : 
[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [4]:
#addition 
"""
addition of two matrix(suppose a and b matrix ) means addition of every 
a(i,j) and b(i,j) of a and b where i==j
"""
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
res=a+b
res

array([[ 8, 10, 12],
       [14, 16, 18]])