In [1]:
import numpy as np
matrix=np.array([[1,2,3,4],[4,5,6,7]])
print('given matrix : ')
print(matrix)

given matrix : 
[[1 2 3 4]
 [4 5 6 7]]


In [2]:
transposed=matrix.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [3]:
"""
here transpose of a matrix means to transform the rows of a matrix to columns and
transform of the columns into rowa . for example a transpose matrix of an 2x3 matrix 
will form into a 3x2 matrix 
"""

'\nhere transpose of a matrix means to transform the rows of a matrix to columns and\ntransform of the columns into rowa . for example a transpose matrix of an 2x3 matrix \nwill form into a 3x2 matrix \n'